apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: iqb3ncdyq-go 
  janus-idp.io/tekton: iqb3ncdyq-go
  backstage.io/kubernetes-id: iqb3ncdyq-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: iqb3ncdyq-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml